### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by boradesanket13** [Sanket1308/Diabetes-prediction-webapp#1]

**Comment by SattyamSamania** [comment]
Hey @boradesanket13 Can I work on this issue. Also Suggest what should be improved in the readme

**Comment by boradesanket13** [comment]
[Follow this website](https://readme.so/)
Contribute well.

**Comment by boradesanket13** [comment]
@SattyamSamania Any progress? If you have any doubts feel free to ask here!

**Comment by SattyamSamania** [comment]
> @SattyamSamania Any progress? If you have any doubts feel free to ask here!

@boradesanket13 Yes working on this

**Comment by SattyamSamania** [comment]
> @SattyamSamania Any progress? If you have any doubts feel free to ask here!

What should be the order of the Contents. Can I just go with the one mention in the website shared by you?
