### ISSUE TITLE
Add a appropriate Background image

### ISSUE THREAD

**Issue by boradesanket13** [Sanket1308/Diabetes-prediction-webapp#2]

**Comment by ankushj0801** [comment]
I want to  work on this. Please assign it to me. @boradesanket13

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by boradesanket13** [comment]
Share image here before starting the coding

**Comment by ankushj0801** [comment]
![asa](https://user-images.githubusercontent.com/108175698/206195299-6dc26c34-fa17-4ca6-8661-b136ea3ab511.jpg)
What about this?

**Comment by Yogeshlodhi** [comment]
@boradesanket13  Can I work on this?

**Comment by boradesanket13** [comment]
@ankushj0801 
![pexels-anete-lusina-6331082](https://user-images.githubusercontent.com/79108273/207097973-d1e0de76-4193-402b-bd42-8db0ca121c7a.jpg)

**Comment by boradesanket13** [comment]
> @boradesanket13 Can I work on this?

Already assigned to @ankushj0801
