### ISSUE TITLE
Create About Diabetes page

### ISSUE THREAD

**Issue by boradesanket13** [Sanket1308/Diabetes-prediction-webapp#4]

**Comment by 1ananya3** [comment]
I want to work on this. Please assign it to me. Please give me a brief description which will help me to make this page better.

**Comment by boradesanket13** [comment]
Create "About Diabetes" page with content on
- What is diabetes?
- [Why is my blood glucose level high? How does this happen?](https://my.clevelandclinic.org/health/diseases/7104-diabetes-mellitus-an-overview)
- [How common is diabetes?](https://www.who.int/news-room/fact-sheets/detail/diabetes)

You can take information and images from internet (we will change it later)

keep the UI simple [like](https://diabetes.org/diabetes) 
Create an image slider at the bottom of the page like [this](https://diabetes.org/diabetes).

If you any difficulty feel free to ask here. We are labeling this issue as "BONUS". We will give extra points (up to 50) based on your work.

**Comment by Yogeshlodhi** [comment]
@boradesanket13  Please assign this to me
