### ISSUE TITLE
Create "Types of diabetes" page

### ISSUE THREAD

**Issue by boradesanket13** [Sanket1308/Diabetes-prediction-webapp#5]

**Comment by Yogeshlodhi** [comment]
@boradesanket13  Please assign this to me. And kindly give some description of the issue and what content you expect on the site.

**Comment by boradesanket13** [comment]
- [1](https://my.clevelandclinic.org/health/diseases/7104-diabetes-mellitus-an-overview)
- [2](https://www.who.int/news-room/fact-sheets/detail/diabetes)

You can take information and images from internet (we will change it later)
